# Generated by Django 4.0.5 on 2022-06-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_question_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
